In [18]:
import pandas as pd

# panda series

In [20]:
grades = pd.Series([88, 90, 80, 97, 99])
grades

0    88
1    90
2    80
3    97
4    99
dtype: int64

In [21]:
print(grades.mean())

90.8

In [22]:
print(grades.min())

80

In [23]:
print(grades.max())

99

In [24]:
# way #1 to create dataframe
data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35],
    "City": ["SF", "LA", "NY"]
}
data

{'Name': ['Alice', 'Bob', 'Charlie'],
 'Age': [25, 30, 35],
 'City': ['SF', 'LA', 'NY']}

In [25]:
df = pd.DataFrame(data)
df

      Name  Age City
0    Alice   25   SF
1      Bob   30   LA
2  Charlie   35   NY

In [26]:
print(df["Name"])

0      Alice
1        Bob
2    Charlie
Name: Name, dtype: object

In [27]:
df[df["City"] == "SF"]

    Name  Age City
0  Alice   25   SF

In [28]:
df["Age"] = df["Age"] + 1
df

      Name  Age City
0    Alice   26   SF
1      Bob   31   LA
2  Charlie   36   NY

In [29]:
# df["Age"] = pd.Series([1, 2, 3])
# df

In [30]:
df["Senior"] = df["Age"] > 30
df

      Name  Age City  Senior
0    Alice   26   SF   False
1      Bob   31   LA    True
2  Charlie   36   NY    True

In [31]:
df.loc[0, :]
# df.loc[row, column], : includes all

Name      Alice
Age          26
City         SF
Senior    False
Name: 0, dtype: object

In [32]:
print(df.loc[0, :])

Name      Alice
Age          26
City         SF
Senior    False
Name: 0, dtype: object

In [33]:
print(df.iloc[0, :])

Name      Alice
Age          26
City         SF
Senior    False
Name: 0, dtype: object